### ISSUE TITLE
Project - Modernize Tag Related Screens and Surrounding Code

### ISSUE THREAD

**Issue by dandominguez04** [Automattic/simplenote-android#1361]
Fixes: #1355 

This is the main issue for modernizing `Tag` related screens. The modernization strategy was discussed in `pbMoDN-2mx-p2` and defines a new architecture to follow in the `Tag` related screens. 

Internal Link: `pbMoDN-2nu-p2`

### Tests

- [x] Setup test dependencies and infrastructure for UI tests #1362 
- [x] Define and implement tests for `AddTagActivity` (medium tests) #1363
- [x] Define and implement tests for `TagDialogFragment` (medium tests) #1364
- [x] Define and implement tests for `TagsActivity` (medium tests) #1365

### Restructure UI logic using viewmodels

- [x] Add dependencies for Viewmodels, Livedata and setup for Viewmodels (e.g. factory) #1368
- [x] Add `AddTagViewModel` to restructure UI and orchestration logic in `AddTagActivity` #1369
- [x] Add `TagDialogViewModel` to restructure UI and orchestration logic in `TagDialogFragment` #1370
- [x] Add `TagsViewModel` to restructure UI and orchestration logic in `TagsActivity` #1371
- [x] Bug: List of search tags is cleared after leaving and entering the app #1413

### Data management

- [x] Restructure data management logic for `Tag` related screens into a repository using the Repository pattern #1372
- [ ] Add tests for `SimperiumTagsRepository`. The tests must include edge cases for searching special Unicode characters #1403

### Extra tasks
- [x] Setup `Dagger` for Dependency Injection in `Tag` related screens and surrounding code #1374
- [x] Rewrite `Tag` related screens ( `AddTagActivity`, `TagDialogFragment`, `TagActivity`) in Kotlin #1373
- [ ] Integrate `detek` (https://github.com/detekt/detekt) #1447 
- [ ] Define and implement End-to-end (E2E) tests for `Tag` related screens #1366
- [ ] Validate error message in HTML format when an error is found trying to edit a tag #1388 
- [ ] Setup CI script to run instrumentation tests #1367
